### ISSUE TITLE
May meetup first talk

### ISSUE THREAD

**Issue by huima** [clojure-finland/home#11]

**Comment by hjhamala** [comment]
Code quality inspection for Clojure using SonarQube.

**Comment by mhjort** [comment]
Sounds good. How long would the talk be?

**Comment by mhjort** [comment]
@hjhamala I could add this to the meetup program if you confirm that you are in. Is half an hour a good length for the presentation?

**Comment by hjhamala** [comment]
I think that 20 minutes should suffice for this.

**Comment by mhjort** [comment]
Great. I added that to the agenda.
