### ISSUE TITLE
April Meetup First Talk

### ISSUE THREAD

**Issue by sulmanen** [clojure-finland/home#5]
29 April 17.30 at Wunderdog at Mikonkatu 13 Helsinki

Needs first talk

**Comment by freetonik** [comment]
@huima suggested re-running my talk from Dutch Clojure Days 2019, so here I am :)

---

Let’s get inspired by biological evolution and write a decentralized genetic algorithms framework entirely in Clojure and Cljs. Then let’s use it to casually tackle some NP-hard problems by combining the computing power of all devices in the meetup!

**Comment by sulmanen** [comment]
Sounds great! @freetonik I'll add you to the agenda?

**Comment by freetonik** [comment]
Sure! Thanks!

**Comment by sulmanen** [comment]
what's the title and how much time do you needs?

**Comment by freetonik** [comment]
"Decentralized evolutionary computation with Clojure and ClojureScript"

I can shorten it a bit and fit in ~25-30 minutes.

**Comment by sulmanen** [comment]
https://github.com/clojure-finland/home/pull/4
