### ISSUE TITLE
April Meetup third talk

### ISSUE THREAD

**Issue by sulmanen** [clojure-finland/home#6]
29 April 17.30 at Wunderdog at Mikonkatu 13 Helsinki

**Comment by huima** [comment]
I could share our travel notes from Clojuredays in Amsterdam. https://clojuredays.org/

All the talks will be published online, so the talk could also help some people to spot what to watch.

Otherwise it would be a short talk about what the Amsterdam community seemed like.

**Comment by sulmanen** [comment]
shall I put you up?

**Comment by huima** [comment]
Unless other talks emerge this can be a backup talk.

**Comment by sulmanen** [comment]
Ok, I'll go then
